### ISSUE TITLE
Authentifier les utilisateurs via OAuth

### ISSUE THREAD

**Issue by mtthp** [coworking-metz/tickets-backend#29]
Les utilisateurs s'identifient aujourd'hui via le site https://www.coworking-metz.fr/ au travers d'un email et d'un mot de passe. Ces identifiants sont parfois difficiles à retenir dans la mémoire d'un utilisateur (sans l'aide d'un gestionnaire de mot de passe) car ils ne sont entrés que rarement.

La multiplication des services pour les utilisateurs entraînent de facto de s'identifier plusieurs fois. Il serait donc opportun de ne pas augmenter cette charge mentale et de leur facilité l'accès du mieux possible.
C'est pourquoi il est intéressant d'implémenter une authentification OAuth où le site https://www.coworking-metz.fr/ valide l'identité des utilisateurs, au profit d'une authentification par email/mot de passe sur chacun des services.

Pour se faire `tickets-backend` doit rediriger les utilisateurs vers `https://www.coworking-metz.fr/` et attendre que ce dernier renvoie les utilisateurs sur `tickets-backend` pour leur accréditer un accès. Cet accès permettra ensuite de consommer les données de `tickets-backend` comme la présence, les abonnements, etc… selon les besoins du service.

Voici un diagramme de séquence lorsque l'utilisateur clique sur le bouton `Login`

![on-login](https://github.com/coworking-metz/tickets-backend/assets/3807788/bb00e40c-1e21-4d98-8f28-6affab5f1947)

---

Et un autre lorsqu'il arrive sur l'app 

![on-refresh-token diagram](https://github.com/coworking-metz/tickets-backend/assets/3807788/7e83265c-5a64-4af5-ab4c-2b19736029b2)

# To do

- [x] Supprimer le code lié aux divers authentifications inutilisées.
- [x] Implémenter un endpoint `GET /api/auth/login` qui redirige l'utilisateur sur le plugin OAuth de wordpress.
Cet endpoint redirigera l'utilisateur avec un `refreshToken` en query param permettant au client (web ou mobile) de récupérer par la suite un `accessToken` sous la forme d'un jeton JWT.
- [x] Implémenter un endpoint `POST /api/auth/tokens { refreshToken }` qui permet de récupérer des jetons JWT `accessToken` et `refreshToken` pour garder une authentification _stateless_
L'`accessToken` sera demandé à chaque endoint pour consommer des données auprès de `tickets-backend` en header sous la forme suivante `Authorisation: Bearer <accessToken>`

**Comment by jdesboeufs** [comment]
Ma première question est "pourquoi la PR de la dernière fois ne suffit pas ?"
Pourquoi `stateless` alors qu'on est actuellement `stateful`, pourquoi un JWT alors qu'on a actuellement un session.

Le système actuel est utilisé par personne, si on change de direction on doit pouvoir le faire pour tous les clients afin de ne pas complexifier la maintenance général de nos outils.
